### PR TITLE
First version of the new Magento module

### PR DESCRIPTION
**Pull request by tmotyl**

### CODE REVIEW

**Comment by tmotyl** [comment]
cla was signed

**Comment by gurneyalex** [comment]
Hello @tmotyl 

indeed I confirm that the information is correct in the OCA database. Please ping me if the CLA bot flags other of your contributions.

**Comment by guewen** [comment]
Thank you again!
That's a very good start to have a clean Magento module.
:+1: for merging

**Comment by yvaucher** [comment]
:+1:  let's merge this

**Pull request merged**
